import Link from "next/link";
import { ArrowRight, Check } from "lucide-react";
import { PublicShell } from "@/components/shared/public-site";

export const metadata = { title: "Pricing | Lumiqs AI", description: "Simple plans for clearer business decisions." };

const plans = [
  { name: "Explorer", price: "$0", period: "forever", description: "Build your first business context and explore the Lumiqs method.", features: ["1 business workspace", "Business profile and memory", "AI Consultant access", "Limited monthly AI usage"], cta: "Start free", href: "/sign-up", featured: false },
  { name: "Founder", price: "$29", period: "per month", description: "For founders making decisions every week and turning insight into motion.", features: ["Up to 3 workspaces", "Unlimited saved insights", "Analysis and market research", "Strategy and execution plans", "Professional reports"], cta: "Choose Founder", href: "/sign-up", featured: true },
  { name: "Studio", price: "$79", period: "per month", description: "For consultants and small teams managing multiple decision trails.", features: ["Unlimited workspaces", "Higher AI usage limits", "Combined reports and PDF export", "Priority support", "Advanced workspace controls"], cta: "Talk to us", href: "/contact", featured: false },
];

export default function PricingPage() {
  return <PublicShell><main><section className="mx-auto max-w-7xl px-5 pb-16 pt-20 text-center lg:px-8 lg:pt-28"><p className="text-xs font-semibold uppercase tracking-[.22em] text-indigo-300">Pricing that stays legible</p><h1 className="mx-auto mt-5 max-w-3xl text-5xl font-semibold tracking-tight text-white md:text-6xl">Start with one decision. Grow into a system.</h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-slate-400">Use Lumiqs free while you shape your context. Upgrade when the quality of your decisions becomes a weekly operating habit.</p></section><section className="mx-auto grid max-w-7xl gap-4 px-5 pb-24 md:grid-cols-3 lg:px-8">{plans.map((plan) => <article key={plan.name} className={`relative flex flex-col border p-7 ${plan.featured ? "border-indigo-300/50 bg-indigo-300/[.08] shadow-2xl shadow-indigo-950/30" : "border-white/10 bg-white/[.025]"}`}>{plan.featured && <span className="absolute right-5 top-5 rounded-full bg-indigo-400/15 px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[.16em] text-indigo-200">Most useful</span>}<h2 className="text-xl font-medium text-white">{plan.name}</h2><p className="mt-4 min-h-12 text-sm leading-6 text-slate-500">{plan.description}</p><div className="mt-8"><span className="text-4xl font-semibold text-white">{plan.price}</span><span className="ml-2 text-sm text-slate-500">{plan.period}</span></div><Link href={plan.href} className={`mt-8 inline-flex items-center justify-center gap-2 rounded-lg px-4 py-3 text-sm font-medium ${plan.featured ? "bg-indigo-500 text-white hover:bg-indigo-400" : "border border-white/15 text-slate-200 hover:bg-white/5"}`}>{plan.cta} <ArrowRight className="h-3.5 w-3.5" /></Link><ul className="mt-8 space-y-4 border-t border-white/10 pt-7">{plan.features.map((feature) => <li key={feature} className="flex gap-3 text-sm text-slate-400"><Check className="h-4 w-4 shrink-0 text-indigo-300" />{feature}</li>)}</ul></article>)}</section><section className="mx-auto max-w-3xl px-5 pb-24 text-center lg:px-8"><p className="text-sm leading-7 text-slate-500">Plans and usage limits may change during the product preview. Lumiqs does not sell outcomes, and AI usage should be evaluated alongside the quality of your own business evidence.</p></section></main></PublicShell>;
}
