import Link from "next/link";
import { ArrowLeft, ShieldCheck } from "lucide-react";
import { PublicFooter, PublicHeader } from "./public-site";

export interface PolicySection { title: string; body: string; bullets?: string[] }

export function PolicyPage({ title, eyebrow, updated, intro, sections }: { title: string; eyebrow: string; updated: string; intro: string; sections: PolicySection[] }) {
  return <div className="min-h-screen bg-slate-950 text-white"><PublicHeader /><main className="mx-auto max-w-4xl px-5 py-16 lg:px-8 lg:py-24"><Link href="/" className="inline-flex items-center gap-2 text-sm text-slate-500 transition-colors hover:text-white"><ArrowLeft className="h-4 w-4" /> Back to Lumiqs</Link><div className="mt-12 border-b border-white/10 pb-10"><p className="text-xs font-semibold uppercase tracking-[.22em] text-indigo-300">{eyebrow}</p><h1 className="mt-4 text-4xl font-semibold tracking-tight text-white md:text-5xl">{title}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-400">{intro}</p><p className="mt-6 text-xs text-slate-600">Last updated: {updated}</p></div><div className="mt-12 space-y-12">{sections.map((section) => <section key={section.title}><h2 className="text-xl font-semibold text-white">{section.title}</h2><p className="mt-4 whitespace-pre-line text-sm leading-7 text-slate-400">{section.body}</p>{section.bullets && <ul className="mt-4 space-y-3">{section.bullets.map((bullet) => <li key={bullet} className="flex gap-3 text-sm leading-6 text-slate-400"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-indigo-400" />{bullet}</li>)}</ul>}</section>)}</div><div className="mt-16 flex items-start gap-3 border border-indigo-400/20 bg-indigo-400/5 p-5"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-indigo-300" /><p className="text-sm leading-6 text-slate-400">These pages are product templates, not legal advice. Have them reviewed by qualified counsel before commercial launch.</p></div></main><PublicFooter /></div>;
}
