export interface PlaybookEntry {
  id: string;
  topic: string;
  keywords: string[];
  guidance: string;
}

// Curated Lumiqs business decision playbook. This is retrieval context, not customer data.
export const BUSINESS_PLAYBOOK: PlaybookEntry[] = [
  { id: 'customer-discovery', topic: 'Customer discovery', keywords: ['customer', 'interview', 'problem', 'pain', 'discovery', 'icp'], guidance: 'Start with 5-10 interviews with a narrowly defined customer segment. Ask about recent behavior, current alternatives, urgency, budget, and the cost of inaction. Avoid leading questions and treat stated interest as weaker evidence than observed behavior or payment.' },
  { id: 'icp-definition', topic: 'Ideal customer profile', keywords: ['icp', 'ideal', 'customer', 'segment', 'persona', 'target'], guidance: 'Define an ICP using firmographic or situational qualifiers, a painful job-to-be-done, trigger events, access to budget, and a reachable acquisition channel. Prefer a segment where the problem is frequent, expensive, and already being solved imperfectly.' },
  { id: 'positioning', topic: 'Positioning', keywords: ['position', 'positioning', 'differentiate', 'message', 'category', 'brand'], guidance: 'Use a clear positioning chain: for a specific customer, who has a specific problem, the product is a category or approach that delivers a concrete outcome, unlike the main alternative. Test messages in conversations and conversion data before polishing brand language.' },
  { id: 'value-proposition', topic: 'Value proposition', keywords: ['value', 'benefit', 'outcome', 'promise', 'landing', 'copy'], guidance: 'Lead with the customer outcome and proof, not a list of features. A strong value proposition makes the target customer, painful situation, promised change, and reason to believe obvious within seconds.' },
  { id: 'pricing-foundation', topic: 'Pricing', keywords: ['price', 'pricing', 'charge', 'monetize', 'revenue', 'plan'], guidance: 'Price against customer value and willingness to pay, not internal effort alone. Start with a simple offer, define the value metric, test price ranges in real sales conversations, and track activation, conversion, retention, expansion, and support burden.' },
  { id: 'pricing-experiments', topic: 'Pricing experiments', keywords: ['price', 'experiment', 'test', 'discount', 'trial', 'conversion'], guidance: 'Change one pricing variable at a time. Test packaging, annual versus monthly commitment, feature limits, and discount policy with a defined hypothesis. Do not interpret a short-term conversion lift as success if retention or gross margin deteriorates.' },
  { id: 'go-to-market', topic: 'Go-to-market', keywords: ['gtm', 'go-to-market', 'launch', 'acquisition', 'channel', 'growth'], guidance: 'Choose one primary wedge: a segment, urgent use case, and channel where the founder can learn quickly. Sequence the motion as discovery, proof, repeatable acquisition, activation, retention, and expansion rather than attempting every channel at once.' },
  { id: 'first-customers', topic: 'First customers', keywords: ['first', 'customers', 'early', 'sales', 'founder', 'traction'], guidance: 'For early traction, use founder-led outreach, warm introductions, communities, partnerships, and targeted content. Personalize around a specific trigger and ask for a concrete next step. Capture objections as product and positioning evidence.' },
  { id: 'sales-process', topic: 'Sales process', keywords: ['sales', 'pipeline', 'prospect', 'demo', 'close', 'qualification'], guidance: 'Define qualification around problem severity, current alternative, authority, timing, and budget access. Keep a small pipeline with explicit next steps and dates. Review lost deals by reason instead of labeling them simply as bad leads.' },
  { id: 'activation', topic: 'Activation', keywords: ['activation', 'onboarding', 'aha', 'first value', 'setup', 'adoption'], guidance: 'Define the first meaningful customer outcome and measure time-to-value. Remove setup friction, guide users to one successful workflow, and use qualitative observation to find where new users stall.' },
  { id: 'retention', topic: 'Retention', keywords: ['retention', 'churn', 'renewal', 'engagement', 'habit', 'customer success'], guidance: 'Retention is usually driven by recurring value, not reminders alone. Identify the behavior that predicts renewal, make that behavior easier, and interview churned customers about the event or unmet expectation that preceded leaving.' },
  { id: 'market-sizing', topic: 'Market sizing', keywords: ['market', 'tam', 'sam', 'som', 'size', 'growth'], guidance: 'Separate verified facts, estimates, and assumptions. Prefer a bottom-up estimate based on reachable customers and realistic annual value. A large top-down market does not prove a reachable wedge or willingness to pay.' },
  { id: 'competitor-analysis', topic: 'Competitor analysis', keywords: ['competitor', 'competition', 'alternative', 'swot', 'threat'], guidance: 'Analyze the customer alternative, not just named companies. Compare target segment, job served, promise, distribution, pricing evidence, strengths, weaknesses, and switching friction. Mark unavailable information rather than inventing facts.' },
  { id: 'experimentation', topic: 'Experiment design', keywords: ['experiment', 'hypothesis', 'validate', 'evidence', 'test', 'mvp'], guidance: 'Write every experiment as a hypothesis, target behavior, smallest test, success threshold, timebox, and decision rule. Choose evidence proportional to the risk: interviews for problem risk, pre-sales for willingness to pay, and usage data for retention risk.' },
  { id: 'metrics', topic: 'Business metrics', keywords: ['metric', 'kpi', 'analytics', 'measure', 'dashboard', 'north star'], guidance: 'Use a small metric tree: acquisition, activation, retention, revenue, and referral. Pair a lagging outcome with leading behaviors. Avoid vanity metrics unless they explain a decision or causal path.' },
  { id: 'unit-economics', topic: 'Unit economics', keywords: ['cac', 'ltv', 'margin', 'unit economics', 'payback', 'cost'], guidance: 'Track contribution margin, acquisition cost by channel, payback period, retention, and expansion. Treat early estimates as directional and state the assumptions behind them. Growth that worsens contribution economics needs a deliberate reason.' },
  { id: 'cash-priorities', topic: 'Cash and priorities', keywords: ['cash', 'runway', 'budget', 'priority', 'focus', 'burn'], guidance: 'Prioritize work by expected learning or economic impact divided by effort and risk. Protect runway by distinguishing must-learn assumptions from nice-to-have improvements, and set a weekly decision review.' },
  { id: 'strategy', topic: 'Strategy', keywords: ['strategy', 'strategic', 'choice', 'focus', 'moat', 'advantage'], guidance: 'Strategy is a set of choices about where to play, how to win, and what not to do. Make trade-offs explicit, connect each choice to evidence, and define the capability or advantage that becomes stronger with repeated execution.' },
  { id: 'execution', topic: 'Execution planning', keywords: ['execution', 'roadmap', 'task', 'milestone', 'weekly', 'plan'], guidance: 'Translate strategy into a short sequence of outcomes, owners, dependencies, and measurable acceptance criteria. Limit weekly priorities, surface blocked work early, and review outcomes rather than activity volume.' },
  { id: 'risk-management', topic: 'Risk management', keywords: ['risk', 'failure', 'uncertain', 'assumption', 'mitigate', 'downside'], guidance: 'List the assumptions that could invalidate the plan, rank them by impact and uncertainty, and test the most dangerous one first. Pair each major risk with an early signal, mitigation, and fallback decision.' },
  { id: 'founder-led-growth', topic: 'Founder-led growth', keywords: ['founder', 'content', 'community', 'network', 'growth', 'authority'], guidance: 'Founder-led growth works when the founder repeatedly shares useful insight with a specific audience and creates direct paths to a valuable conversation. Consistency and customer evidence matter more than broad reach.' },
  { id: 'b2b-saas', topic: 'B2B SaaS', keywords: ['saas', 'b2b', 'subscription', 'software', 'annual', 'seat'], guidance: 'For B2B SaaS, connect onboarding to a business outcome, understand the buying committee, and distinguish user value from buyer value. Keep packaging legible and measure usage that predicts renewal rather than raw logins.' },
  { id: 'service-business', topic: 'Service businesses', keywords: ['service', 'consulting', 'agency', 'delivery', 'capacity', 'retainer'], guidance: 'Service businesses should protect delivery quality while productizing repeatable outcomes. Define scope, capacity, margin, proof, and a path from bespoke work to repeatable packages or retainers.' },
  { id: 'decision-quality', topic: 'Decision quality', keywords: ['decision', 'decide', 'recommendation', 'choice', 'evidence', 'confidence'], guidance: 'Separate facts, estimates, assumptions, recommendations, and items requiring validation. State the decision, alternatives considered, evidence, downside, reversibility, and the next signal that would change the choice.' },
  { id: 'ethical-ai', topic: 'Responsible AI use', keywords: ['ai', 'ethics', 'privacy', 'bias', 'accuracy', 'safety'], guidance: 'AI recommendations are decision support, not guarantees. Do not expose confidential data across businesses, do not fabricate statistics or competitor facts, and encourage validation for legal, financial, medical, safety, and high-impact decisions.' },
];
